#!/usr/bin/env bash

set -e

# Import the appropriate bash commons libraries
readonly BASH_COMMONS_DIR="/opt/gruntwork/bash-commons"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly DEFAULT_KAPACITOR_VERSION="1.5.2"
readonly DEFAULT_TEMP_KAPACITOR_CONFIG_FILE_PATH="/tmp/config/kapacitor.conf"
readonly DEFAULT_KAPACITOR_CONFIG_FILE_PATH="/etc/kapacitor/kapacitor.conf"
readonly DEFAULT_KAPACITOR_DIR="/opt/kapacitor"
readonly DEFAULT_KAPACITOR_BIN_DIR="$DEFAULT_KAPACITOR_DIR/bin"

readonly INFLUXDB_COMMONS_SRC_DIR="$SCRIPT_DIR/../influxdb-commons"
readonly INFLUXDB_COMMONS_INSTALL_DIR="/opt/influxdb-commons"

if [[ ! -d "$BASH_COMMONS_DIR" ]]; then
  echo "ERROR: this script requires that bash-commons is installed in $BASH_COMMONS_DIR. See https://github.com/gruntwork-io/bash-commons for more info."
  exit 1
fi

source "$BASH_COMMONS_DIR/assert.sh"
source "$BASH_COMMONS_DIR/log.sh"
source "$BASH_COMMONS_DIR/os.sh"

function print_usage {
  echo
  echo "Usage: install-kapacitor [options]"
  echo
  echo "This script can be used to install Kapacitor and its dependencies. This script has been tested with Ubuntu 18.04 and Amazon Linux 2."
  echo
  echo "Options:"
  echo
  echo -e "  --version\t\tThe version of Kapacitor to install. Default: $DEFAULT_KAPACITOR_VERSION."
  echo -e "  --config-file\t\tPath to a custom configuration file. Default: $DEFAULT_TEMP_KAPACITOR_CONFIG_FILE_PATH"

  echo
  echo "Example:"
  echo
  echo "  install-kapacitor --version $DEFAULT_KAPACITOR_VERSION --config-file $DEFAULT_TEMP_KAPACITOR_CONFIG_FILE_PATH"
}

function install_kapacitor_scripts {
  local -r dest_dir="$1"

  local -r run_kapacitor_src="$SCRIPT_DIR/../run-kapacitor/run-kapacitor"
  local -r run_kapacitor_dest="$dest_dir/run-kapacitor"

  log_info "Copying $run_kapacitor_src to $run_kapacitor_dest"
  sudo mkdir -p "$dest_dir"
  sudo cp "$run_kapacitor_src" "$run_kapacitor_dest"
}

function install_influxdb_commons {
  local -r src_dir="$1"
  local -r dest_dir="$2"

  log_info "Copying $src_dir to $dest_dir"
  sudo cp -r "$src_dir" "$dest_dir"
}

function install_kapacitor_on_ubuntu {
  local -r version="$1"

  log_info "Installing Kapacitor"
  wget "https://dl.influxdata.com/kapacitor/releases/kapacitor_${version}_amd64.deb"
  sudo dpkg -i "kapacitor_${version}_amd64.deb"
}

function install_kapacitor_on_amazon_linux {
  local -r version="$1"

  log_info "Installing Kapacitor"
  wget "https://dl.influxdata.com/kapacitor/releases/kapacitor-${version}.x86_64.rpm"
  sudo yum localinstall -y "kapacitor-${version}.x86_64.rpm"
}

function install_kapacitor {
  local version="$DEFAULT_KAPACITOR_VERSION"
  local config_file="$DEFAULT_TEMP_KAPACITOR_CONFIG_FILE_PATH"

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --help)
        print_usage
        exit
        ;;
      --version)
        assert_not_empty "$key" "$2"
        version="$2"
        shift
        ;;
      --config-file)
        assert_not_empty "$key" "$2"
        config_file="$2"
        shift
        ;;
      *)
        echo "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_is_installed "sudo"
  assert_is_installed "wget"

  if os_is_ubuntu "18.04"; then
    install_kapacitor_on_ubuntu "$version"
  elif os_is_amazon_linux "2"; then
    install_kapacitor_on_amazon_linux "$version"
  else
    log_error "This script only supports Ubuntu 18.04 and Amazon Linux 2."
    exit 1
  fi

  # Disable the installed systemd service to prevent it from starting up on boot.
  # The 'run-kapacitor' script will be used to start the service after properly configuring it
  sudo systemctl disable kapacitor.service

  sudo mv "$config_file" "$DEFAULT_KAPACITOR_CONFIG_FILE_PATH"
  install_kapacitor_scripts "$DEFAULT_KAPACITOR_BIN_DIR"
  install_influxdb_commons "$INFLUXDB_COMMONS_SRC_DIR" "$INFLUXDB_COMMONS_INSTALL_DIR"
}

install_kapacitor "$@"
